name: Copilot Setup Steps

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  setup:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install requirements.txt
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Verify installation
      run: |
        python --version
        jupyter --version
        jupyter lab --version
        python -c "import transformers; print(f'Transformers: {transformers.__version__}')"
        python -c "import torch; print(f'PyTorch: {torch.__version__}')"
        python -c "import jupyter; print('Jupyter installed successfully')"